### ISSUE TITLE
Search single character must use () to enclose it.

### ISSUE THREAD

**Issue by gxt-kt** [nvim-pack/nvim-spectre#103]
Search single character must use () to enclose it.

Just like i want to search "a" character. If i input "a" it will not search. I must input "(a)" it will search "a". It only happen in single character. If i input two or more character it will search normally.
![image](https://user-images.githubusercontent.com/47113549/216117056-fdb490b5-885e-4cb5-8055-8f8560e36ce1.png)
![image](https://user-images.githubusercontent.com/47113549/216117144-cee29ec4-5828-45c0-be5c-328b8ea1a8b9.png)

Actually i don't know the bracket() means here. Is it possiable to search one character without () ?

Thank you.

**Comment by windwp** [comment]
on default it search 3 character. i do that because if you search 1 character on big project it can crash because too many result.
btw i still prefer search by / on current buffer

**Comment by gxt-kt** [comment]
Thank you. l understand the reason. 
I use this plugin to search one character because l want add something to begaining of all lines. So l must search "^" in regular expression. 
Whatever , this plugin is very useful.
