### ISSUE TITLE
Change the buffer background highlight

### ISSUE THREAD

**Issue by serhez** [nvim-pack/nvim-spectre#111]
Could it be possible to add an option to change the highlight of the Spectre buffer's background? As I understand it, you have not created highlight groups that can be overridden, and instead we only have config options to change the highlights; it would be nice to have also highlight groups. In any case, it would be good to add the buffer's background to the config too.

Thanks for considering!

**Comment by EpsilonKu** [comment]
Yeah, will make option to change highlight. Planing for next holiday
