### ISSUE TITLE
Suggested feature/improvement, to use rg --replace instead

### ISSUE THREAD

**Issue by asmodeus812** [nvim-pack/nvim-spectre#112]
It would be great if the plugin also supported the rg --replace instead of using sed/oxi, this will give it an advantage of being able to use the same search and replace patterns supported by rg. The rg --replace command is also useful for allowing previews, as it naturally is a preview command which does not change the file rather rg allows you to only preview the changes replacing serach with replace pattern will have on each line in the file. Would it be possible for this to be added as a new replacement engine ?

**Comment by windwp** [comment]
currently the replace method doesn't need to re run command . It update the UI highlight by lua. it use  vim regex or rust . 
if you want to run rg --replace only when you replace it is easy. 
but if you want to match the change on preview UI then it need a lot of change.
