### ISSUE TITLE
Replacing causes new files with the "-E" suffix

### ISSUE THREAD

**Issue by gaborvecsei** [nvim-pack/nvim-spectre#118]
How can I configure `spectre` to replace the selections inplace?

**Comment by lexuancuong** [comment]
I got the same issue. I hope to have a solution to this problem.

**Comment by NeilGirdhar** [comment]
Is there a way to make this automatically happen on mac and not on linux?

Something like:

```
require("spectre").setup({
  replace_engine = {
    ["sed"] = {
      cmd = "sed",
      args = {
        "-i",
	"",
	"-E",
      } if OSX else {},
    },
  },
```

**Comment by jeanlucthumm** [comment]
@NeilGirdhar 

Maybe `vim.loop.os_uname().sysname == 'Darwin'`?
