### ISSUE TITLE
Replacing '@' symbol

### ISSUE THREAD

**Issue by theoribeiro** [nvim-pack/nvim-spectre#124]
Trying to use nvim-spectre to replace a string with an '@' symbol in it using sed but been having the following error show up:

   Error  14:49:49 msg_show.lua_error Error executing vim.schedule lua callback: Vim:E866: (NFA regexp) Misplaced @
stack traceback:
	[C]: in function 'substitute'
	...l/share/nvim/lazy/nvim-spectre/lua/spectre/regex/vim.lua:20: in function 'replace_all'
	....local/share/nvim/lazy/nvim-spectre/lua/spectre/init.lua:469: in function 'on_result'
	...share/nvim/lazy/nvim-spectre/lua/spectre/search/base.lua:66: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

What I'm trying to do is replace the name of a NPM package in our project. Using sed like: 
sed "s/@package\/name/@newpackage\/name/" works just fine. However, I get the error above if I'm using spectre. 

I tried escaping the '@' in bothe the Search and Replace fields but it also doesn't work. 

Any insights on why this might be happening or is this a bug?

**Comment by windwp** [comment]
i think it is a bug :)
you can switch from sed to oxi

**Comment by theoribeiro** [comment]
That would be great if I could compile it on my Mac M1. Can't find a way to build for arm64 architecture :(
