### ISSUE TITLE
I got error when running replace.

### ISSUE THREAD

**Issue by peter-lyr** [nvim-pack/nvim-spectre#141]
![image](https://github.com/nvim-pack/nvim-spectre/assets/55801796/522c1188-4d74-49bc-bbef-77a1a8d76e79)

![image](https://github.com/nvim-pack/nvim-spectre/assets/55801796/34d2ae80-fdfa-40d5-a462-cc65bb8c9b59)

![image](https://github.com/nvim-pack/nvim-spectre/assets/55801796/df1f7a29-c1a5-4208-a7bc-e1567b9dd608)

![image](https://github.com/nvim-pack/nvim-spectre/assets/55801796/519550e8-9a28-4056-8476-50b69694a32f)

On the other hands, `^s` matches not only starting of line. Why?

**Comment by EpsilonKu** [comment]
Emm... You should write under `Search` not `Replace`

**Comment by EpsilonKu** [comment]
Did u installed `sed` tool?
