### ISSUE TITLE
Question in documentation

### ISSUE THREAD

**Issue by Sleepful** [nvim-pack/nvim-spectre#145]
From README:
> It has different regex sytax compared to the rg command and replace command sed so be careful when replacing text.

Well, it is good to know that it has regex syntax, but it does not tell me which syntax I should base my searches on! Does it have a name? Like `pcre2` for example.

**Comment by EpsilonKu** [comment]
It's more like question of `BurntSushi/ripgrep`.

**Comment by EpsilonKu** [comment]
https://docs.rs/regex/1.8.4/regex/#syntax
