### ISSUE TITLE
Can't replace by sed

### ISSUE THREAD

**Issue by LintaoAmons** [nvim-pack/nvim-spectre#146]
I have the same config both on my old mac and new m1 mac.

But can't replace in the m1 mac, it shows the following error (I have `sed` command available on the new m1 mac)

<img width="1709" alt="image" src="https://github.com/nvim-pack/nvim-spectre/assets/95092244/6b20a261-71fd-4baa-b4e4-35bf5df25024">

It says `gsed` not available?

**Comment by EpsilonKu** [comment]
https://unix.stackexchange.com/questions/390040/gsed-command-not-found-on-macos-with-homebrew

**Comment by LintaoAmons** [comment]
Run `brew install gnu-sed` to solve this.
