### ISSUE TITLE
Bug: Help/option menu border only displays on 3 sides

### ISSUE THREAD

**Issue by Subjective** [nvim-pack/nvim-spectre#149]
As the title says, the help/option menu border only displays on 3 sides for both split and vsplit layouts. Interestingly enough, the remaining border does appear after resizing the spectre window beyond a certain threshold.

![image](https://github.com/nvim-pack/nvim-spectre/assets/56745535/b90b70f8-aa51-4cd9-b932-331d24e667be)

**Comment by windwp** [comment]
yeah i already try to but i don't know why plenary.popup do that. maybe we can switch to use nvim_open_win()

**Comment by EpsilonKu** [comment]
@Subjective Can u try #158 ?
