### ISSUE TITLE
Add exclude Option

### ISSUE THREAD

**Issue by sp71** [nvim-pack/nvim-spectre#155]
Currently search replace and path are offered. VsCode offers an additional exclude path which is very helpful when certain paths should remain untouched. Thoughts on adding this feature?

**Comment by ManiaciaChao** [comment]
You don't. The "Path" panel is not actually the equivalent of VSCode's "Include". 
> It can filter search by path glob (filetype).

Just use glob instead, e.g. `!{**/node_modules/**, **/dist/**}`.

**Comment by windwp** [comment]
ManiaciaChao is correct. you can exclude it by add `!`. multiple path by can split by space
