### ISSUE TITLE
How to replace?

### ISSUE THREAD

**Issue by maxkorolev** [nvim-pack/nvim-spectre#163]
I am sorry, for the stupid question, but how to execute command to replace? 
omg, it is really beautiful plugin, but I have spent 20mins reading all docs and issues and still have no idea)))

Could you please add to the docs how to actually execute replacement? On the gif it is not clear what was pressed to replace

**Comment by blurname** [comment]
Just press `?` in Spectre window, will show the mappings.
\<leader\>rc for single line replacement
\<leader\>R for all replacement
![image](https://github.com/nvim-pack/nvim-spectre/assets/50226652/b5811b7f-e7ff-4a62-a0ff-01f1ddaabaf7)

**Comment by maxkorolev** [comment]
thank you!!!
