### ISSUE TITLE
Option to retain buffer after closing window

### ISSUE THREAD

**Issue by lorefnon** [nvim-pack/nvim-spectre#166]
Hello, thanks a lot for creating this extension - it has become an integral part of my workflow.

Currently this plugin creates an [unlisted buffer](https://github.com/nvim-pack/nvim-spectre/blob/411cee67fe3f8242023eb8d9edafefbbfb2d06f1/lua/spectre/ui.lua#L151). I'd like to request for a config option that makes this listed by default.  Would you be open to adding that ?

**Comment by EpsilonKu** [comment]
What about to just make option on config? I prefer unlisted buffer more.

**Comment by lorefnon** [comment]
Yes, thats what I meant - sorry if the wording was confusing. 

I meant that once I set this config option, the buffer that spectre will create will be listed  by default.
