### ISSUE TITLE
Toggled items indistinguishable

### ISSUE THREAD

**Issue by iluuu1994** [nvim-pack/nvim-spectre#167]
Thank you for your Spectre!

![image](https://github.com/nvim-pack/nvim-spectre/assets/1752683/63b0100c-5d7e-48f0-86a9-fab76fb275eb)

I toggled the first item using `dd`. However, the text is completely indistinguishable from non-toggled items. When I replace the text, it seems like the flag is set correctly as only the second item was replaced. I'm using LunarVim, I'm not sure if their theme might be to blame, or whether it's a Spectre problem.

If Spectre can't avoid this problem, maybe an option would be to prepend the text with an icon for disabled items.

Thank you!

*Edit*: Oh, I also just realized that the output lists both old and new text. I suppose these are meant to be colored / crossed out.

**Comment by iluuu1994** [comment]
Oh. This only breaks if I'm in config.lua and make an edit. LunarVim re-sources the config file, which for some reason breaks all the colors/styles inside Spectre. If you don't think this is worth fixing, feel free to close this issue.

**Comment by EpsilonKu** [comment]
Hot-reload is bloody hell. It set plugin state to default. So there is no need to fix it. Closing
