### ISSUE TITLE
Broken highlighting after 3869b31

### ISSUE THREAD

**Issue by jdah** [nvim-pack/nvim-spectre#169]
Hi, thanks so much for this plugin - I love it.

Recently updated after a while and noticed that syntax highlighting, strikethrough, etc. seems to be broken, which makes the plugin very hard to use:
<img width="918" alt="image" src="https://github.com/nvim-pack/nvim-spectre/assets/20308439/037048e3-87d5-483a-a589-5862f2878315">

and I've tracked it down to commit 3869b31, as if I revert to the commit immediately before (6e26a19735bf294930140e4ebfe1b434cc6d26d1) everything seems to be working fine:
<img width="919" alt="image" src="https://github.com/nvim-pack/nvim-spectre/assets/20308439/82154773-bb7f-4d18-8332-01afc490c0da">

I'm guessing this has something to do with my highlight groups, but I'm not entirely sure what the reasoning is behind throwing things in "Comment" instead of "DiffDelete" - is this issue on my end? Nothing in my configs is changed between the two screenshots above aside from the commit for `nvim-spectre`.

Thanks :)

**Comment by EpsilonKu** [comment]
The problem occurs when you load colorscheme after nvim-spectre. There was some problem with direct linking of highlight. So it creates highlight seperately from vim native highlight group. 
Try to load plugin after colorscheme. If it won't work, tell me.

**Comment by jdah** [comment]
That seems to fix it! Thanks.
