### ISSUE TITLE
An error occurs while using spectre for text replacement, When the neotree file explorer window is open

### ISSUE THREAD

**Issue by yongshengzhucn** [nvim-pack/nvim-spectre#170]
<img width="1669" alt="Screenshot 2023-09-30 at 02 09 35" src="https://github.com/nvim-pack/nvim-spectre/assets/16286523/00eee25c-6127-4f37-b8e3-784f8b690990">
I'm currently using neo-tree as a file explorer, but when using the nvim-spectre plugin for search and replace, I'm getting an error.
However, this error did not affect the success of the replacement.

**Comment by yongshengzhucn** [comment]
`  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = function(_, opts)
      table.insert(opts.open_files_do_not_replace_types, "spectre_panel")
      opts.filesystem.use_libuv_file_watcher = false
    end,
  },
`

I have verified that the error occurs when filesystem.use_libuv_file_watcher=true is set.

**Comment by EpsilonKu** [comment]
Seems like you got error when replacing text. It's more like issue of Neo-tree or replace utility. Guess that replacing happens by replacing file or smth like that. For millisecond it disappears.
