### ISSUE TITLE
Highlights when doing search and replace are not working

### ISSUE THREAD

**Issue by alextricity25** [nvim-pack/nvim-spectre#178]
Search and replace features are not highlighting as they are suppose to.

For example, in the below screenshot I am searching for `plugins_lazy`, and replacing it with `Something`, but you'll notice that the highlights are not showing up.

<img width="696" alt="image" src="https://github.com/nvim-pack/nvim-spectre/assets/4964964/153be4f1-be26-45f5-ae57-12e490f8a5f2">

I am using the `gruvbox-material` colorsheme and have `termguicolors` set.

**Comment by Zeioth** [comment]
This is `help wanted`. [I sent a PR](https://github.com/nvim-pack/nvim-spectre/pull/172) to fix ocassional crashes on the hl function. Seems like that function need some attention.

**Comment by EpsilonKu** [comment]
It's more like my commit problem. If u load highlight after plugin. It won't highlight. Will try something.
