### ISSUE TITLE
How can I unmap tab?

### ISSUE THREAD

**Issue by habanerotostitos** [nvim-pack/nvim-spectre#179]
I use the tab keymap for something else and would like to unmap it from Spectre but couldn't figure out how. 

I tried to follow the documentation for other mappings and just replaced the example with "tab" instead, but it didn't seem to work.

This is what I tried to remap it off of \<Tab\> and into \<S-Tab\>

`
mapping = {
    ["tab"] = {
        map = "<S-Tab>",
        cmd = "<cmd>lua require('spectre').tab()<cr>",
}
}`

**Comment by EpsilonKu** [comment]
Ahh, it was add recently. Yeah, we should add reconfiguration.

**Comment by xzbdmw** [comment]
Hello what's the state of this

**Comment by EpsilonKu** [comment]
I nearly done #110 after I will do this. Should be easy. Sorry, I was inactive long-time only now recovering.

**Comment by EpsilonKu** [comment]
Can you guys try #211 . Add to `config`  `mapping` without ['tab], ['shift-tab'] or remap to another key: 
```lua 
...
        ['tab'] = {
            map = 'gn',
            cmd = "<cmd>lua require('spectre').tab()<cr>",
            desc = 'next query'
        },
        ['shift-tab'] = {
            map = 'gp',
            cmd = "<cmd>lua require('spectre').tab_shift()<cr>",
            desc = 'previous query'
        },
...
```
