### ISSUE TITLE
Analogy of search_dirs in Telescope

### ISSUE THREAD

**Issue by defr0std** [nvim-pack/nvim-spectre#184]
Hi,

Thanks for the awesome plugin!

Is there a way to have an analogy of the `search_dirs` in Telescope?

For example, with Telescope you can write:

```
require('telescope.builtin').live_grep(
   { search_dirs = ['/dira', '/dirb'] })   
```

and it will limit the search only to /dira  and /dirb.

The path option in nvim-spectre is not really the same. For `rg`, it adds the -g option. So the search is performed in the *cwd* with the globs specified in -g. Which is not the same as searching in the specific dirs only.

In my case, I am working on a big monorepo, but usually only in specific subdirectories. So instead of searching in the entire monorepo (which is very slow), I am searching directly in the directories of interest.

The command that I would like to reproduce is `rg --... search_text /dir1 /dir2`

**Comment by windwp** [comment]
you can set it on open function    {path ="dira/**  dirb/** !dira/not_include/** " } .

**Comment by defr0std** [comment]
I've explained in the original comment that path is not really the same as searching in the specified directories. The way path option is implemented is that the search is still performed in the cwd, but the files are matched against the path glob.
