### ISSUE TITLE
With lazy.nvim update for spectre, cwd is changing to spectre plugin's directory

### ISSUE THREAD

**Issue by mambusskruj** [nvim-pack/nvim-spectre#186]

**Comment by EpsilonKu** [comment]
Yeah, I can confirm. Making hotfix for that. But it's night right now. Hopefully will be ready tomorrow.

**Comment by EpsilonKu** [comment]
Weird, I can't repeat bug. I guess latest commit fixed it. Can you try to update it?

**Comment by mambusskruj** [comment]
Yes, can't reproduce it either.

**Comment by alex35mil** [comment]
I'm not sure if it's exactly this issue but when I search in the current project, I get results only from one subdirectory.

On the left side is one of the modules of the project, and on the right side is spectre results.

![CleanShot 2023-11-11 at 18 00 46@2x](https://github.com/nvim-pack/nvim-spectre/assets/4244251/a9151900-e80f-4b09-ba70-260d5934ddde)

**Comment by EpsilonKu** [comment]
What is your spectre config?

**Comment by alex35mil** [comment]
@EpsilonKu [here it is](https://github.com/alex35mil/dotfiles/blob/705b79a239af76f2b8027554b05cf15af0e1555b/home/.config/nvim/lua/plugins/spectre.lua)

**Comment by EpsilonKu** [comment]
Hmm, seems normal. Maybe it ignored by .gitignore?

**Comment by alex35mil** [comment]
I don't think so. Here is [my .gitignore](https://github.com/alex35mil/dotfiles/blob/705b79a239af76f2b8027554b05cf15af0e1555b/.gitignore), and I just committed a lot of stuff that is supposed to be searchable but it is not.

**Comment by alex35mil** [comment]
It seems like a problem unrelated to spectre but related to `rg` as it gives the same results in terminal.

**Comment by alex35mil** [comment]
Doh, recently, I switched from home-manager to general symlinking and `~/.config` directory is hidden lol. [Fixed](https://github.com/alex35mil/dotfiles/commit/dfae29d9795860c170266675c4187098a3122915).
