### ISSUE TITLE
Latest Commits Break Spectre

### ISSUE THREAD

**Issue by duncanam** [nvim-pack/nvim-spectre#191]
I am no longer able to use spectre after the latest few commits. 

The error I get:

```
E5108: Error executing vim/_editor.lua:0: Expected lua string
```

I have installed through Lazy, and am using a leader key to use the plugin, through whichkey, on LunarVim. 

When I tell Lazy to roll back the plugin to d20dcf7 "feat: add action select_template", everything is functional as expected. I think either 5a112b4 or dd61fea is breaking things. 

Typing :Spectre does not work either, and returns the same failing error message.

**Comment by EpsilonKu** [comment]
@windwp are you `zztrieuzz`? Hope you can fix it quickly.

**Comment by EpsilonKu** [comment]
Seems like @duncanam has old version of nvim. What is your nvim version?

**Comment by sontixyou** [comment]
2ee3496748cb4284d75c88b9f4e116bfe2dac872 commit confirms that it works!

Neovim version v0.10.0-dev-1572+g64c2c7c40

**Comment by windwp** [comment]
Sorry, I added a small feature. I think it should be fixed in the PR above

**Comment by duncanam** [comment]
Indeed fixed! You guys are speedy and awesome!
