### ISSUE TITLE
Why error: unrecognized escape sequence \/

### ISSUE THREAD

**Issue by brunojoao** [nvim-pack/nvim-spectre#193]
![image](https://github.com/nvim-pack/nvim-spectre/assets/16447379/11d91a1c-4481-42c6-b196-8c9b139d950b)

if place this regex display error

\/

iam in Lubutnu 22.04

**Comment by EpsilonKu** [comment]
Seems like it's an issue of `rg`.

**Comment by loiclaudet** [comment]
within the regex pattern itself, the forward slash is not a special character

that's probably the reason why a parse error is thrown here

you can directly use`/` without character escaping
