### ISSUE TITLE
colors are gone when you change the colorscheme

### ISSUE THREAD

**Issue by dprophete** [nvim-pack/nvim-spectre#196]
spectre works as expected when I start nvim.
<img width="896" alt="image" src="https://github.com/nvim-pack/nvim-spectre/assets/518393/4cf25b3c-010e-46fd-ae8f-15e9a8cd4f55">

But if I ever change my colorscheme (say to switch to a light colorscheme), then the colors are gone:
<img width="894" alt="image" src="https://github.com/nvim-pack/nvim-spectre/assets/518393/c192964e-fb2d-4466-b66d-fdb1758721ae">

(and switching back to the previous colorscheme doesn't help either:
<img width="888" alt="image" src="https://github.com/nvim-pack/nvim-spectre/assets/518393/1eaeea20-8cc8-4d42-90e6-04eb899882b0">
)

I am using: 
```
NVIM v0.9.0-dev-805+g9166116c6-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by didier@didier-m1-mbp.local

Features: +acl +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-9166116/share/nvim"

Run :checkhealth for more info
```

on max os sonoma 14.1.2 (23B92)
and with the latest nvim-spectre (commit a18a580)

**Comment by abilkhan024** [comment]
Hi, I have almost the same setup, and encountaring this bug, did you find any workaround?
