### ISSUE TITLE
Is there a way to open multiple spectre windows at once?

### ISSUE THREAD

**Issue by NullVoxPopuli** [nvim-pack/nvim-spectre#203]
title says it all -- my use case is that I'm needing to do some migrations in an un-statically-typed code base, and need would like to not lose search results (I also have a big monitor, so I could probably have 4 search results panes + a corresponding editing pane for each

**Comment by windwp** [comment]
Sorry no. it use 1 global state so make it run on multiple instance is need a big changes. maybe you can send it to qf or open another nvim  🤣
