### ISSUE TITLE
open_visual({select_word=true}) not taking entire visual selection?

### ISSUE THREAD

**Issue by jacobrreed** [nvim-pack/nvim-spectre#217]
When i visually select a word then use the open_visual command with select_word=true, it only takes the first part of the visually selected word
https://github.com/nvim-pack/nvim-spectre/assets/25580051/0cdb3aff-b92c-4cd9-a1ef-de7f0b171daf

**Comment by EpsilonKu** [comment]
dublicate of #202

**Comment by jacobrreed** [comment]
@EpsilonKu Can we reopen this still doesn't work, also im using oxi if that makes any difference
![image](https://github.com/nvim-pack/nvim-spectre/assets/25580051/f71d9f32-40ba-4595-88fc-85d48e14f81b)
![image](https://github.com/nvim-pack/nvim-spectre/assets/25580051/2b1f85e8-7a11-441e-8aa1-e55f576c4e36)

**Comment by EpsilonKu** [comment]
Sorry, I miread your issue and I had problem opening video. It's different issue, sorry

**Comment by tlowerison** [comment]
Any progress here? I'm noticing this issue as well. For example, when my visual selection is on the word `nvim-spectre`, it will only populate the search query with `spectre`
