### ISSUE TITLE
replace all throw a error

### ISSUE THREAD

**Issue by DreamMaoMao** [nvim-pack/nvim-spectre#223]
![image](https://github.com/nvim-pack/nvim-spectre/assets/30348075/696c23df-4365-4a9e-9524-3ce679ce83ca)

Every replacement will have an error ,but I really don't have this file, so why would it go looking for that file?

**Comment by DreamMaoMao** [comment]
This error does not occur if neo-tree is closed. Is this error due to spectre generating temporary files and quickly deleting them?

**Comment by EpsilonKu** [comment]
Can you send full error? If you run :message command. It shows error

**Comment by EpsilonKu** [comment]
@DreamMaoMao I guess it appears cuz replace tool do file operations. So it's more like neo-tree issue. It's similar to https://github.com/nvim-neo-tree/neo-tree.nvim/issues/914. You should remove ` use_libuv_file_watcher = false` so it won't track files or open issue on neo-tree. Closing this issue. If you think this is spectre problem anyway, please provide full error message.
