### ISSUE TITLE
[Feature Request] Add keymaps to jump to next/previous result item 

### ISSUE THREAD

**Issue by carlos-algms** [nvim-pack/nvim-spectre#224]
It would be great to jump to each result item with a keymap. 

Either extend `Tab` to keep jumping each item
Or something like `]q` and `[q` to go to next/prev 

And maybe allow it to be customizable.

**Comment by EpsilonKu** [comment]
Well, u can go down. I guess you mean just to next/previous file result?

**Comment by carlos-algms** [comment]
Yes, similar to `n` and `N` when using Vim's native `/` search
