### ISSUE TITLE
Replace says DONE but is not happening

### ISSUE THREAD

**Issue by FedeAbella** [nvim-pack/nvim-spectre#230]
I'm sorry I haven't got a lot of info on this, as no errors are thrown, and no messages or anything appear. This is my first try at using Spectre, and ran into this:
![image](https://github.com/nvim-pack/nvim-spectre/assets/65520926/8bdffd10-1ed8-422d-970f-e67f86535b8f)

Same thing happens when running "Replace all". Items say "DONE" but no changes are actually made to any of the files, not even after reopening. Even git doesn't track anything has changed.

This is my spectre plugin file:
```lua
return {
    "nvim-pack/nvim-spectre",
    dependencies = {
        "nvim-lua/plenary.nvim",
    },
    lazy = true,
    cmd = "Spectre",
    config = function()
        require("spectre").setup({
            find_engine = {
                -- rg is map with finder_cmd
                ["rg"] = {
                    cmd = "rg",
                    -- default args
                    args = {
                        "--color=never",
                        "--no-heading",
                        "--with-filename",
                        "--line-number",
                        "--column",
                        "--follow",
                    },
                    options = {
                        ["ignore-case"] = {
                            value = "--ignore-case",
                            icon = "[I]",
                            desc = "ignore case",
                        },
                        ["hidden"] = {
                            value = "--hidden",
                            desc = "hidden file",
                            icon = "[H]",
                        },
                        -- you can put any rg search option you want here it can toggle with
                        -- show_option function
                    },
                },
            },
        })
    end,
}
```
Running on Ubuntu 23.10, and `sed` is definitely available. There are no keymaps overlaps with spectre that may be interfering.

Am I doing something incredibly wrong? Let me know any other info I can get for you, and I'll be happy to do so

**Comment by vad** [comment]
I confirm spectre is not working anymore even in my case (standard setup with sed)

**Comment by windwp** [comment]
_G.__spectre_log = true

can you put it on top of your init.lua. and try to do replace again. i will log the sed command output. maybe you can try to run that command on your terminal.  
underthe hood we only generate that command and run it so i am not sure why it not work on your computer.

**Comment by FedeAbella** [comment]
Here's the output:
```
[nvim-spectre] [DEBUG 21:00:50] /home/fede/.local/share/nvim/lazy/nvim-spectre/lua/spectre/replace/sed.lua:43: replace cmd: sed -i -E ...home/fede/Programming/Salesforce/one-customer-care-sfdc/force-app/main/default/lwc/eventDispatcherLink/eventDispatcherLink.js-meta.xml
```
To note: The filepath appearing in that debug is the last file in the result list

**Comment by windwp** [comment]
are you try to run that command or your terminal

**Comment by FedeAbella** [comment]
That command is incomplete. It has no replace string, it consists only of flags and a filepath

**Comment by Freaksed** [comment]
ok so how would you do this... i am trying to search for (\d+)n and replace with BigInt(\1)
but this does not work either

**Comment by dylan-chong** [comment]
i'm experiencing the same issue. if i have a capture in the regex, the replace will say it works.

Replace Works:
Search
Contacts.checkPermission.mockImplementation.*
Replace
Contacts.checkPermission.mockImplementationPoo

Replace doesn't do anything:
Search
Contacts.checkPermission.mockImplementation(.*)
Replace
Contacts.checkPermission.mockImplementationNooo

**Comment by martazvch** [comment]
Yes same here, replacement with capture groups doesn't work...
