### ISSUE TITLE
How to edit search_paths dynamically?

### ISSUE THREAD

**Issue by guanghechen** [nvim-pack/nvim-spectre#234]
Hi @windwp, thank you for writing this amazing plugin, it saved my life. I noticed that specifying `searched_paths` in the `open` function can optimize search speed, that's a great feature, but I cannot see the option value in the opened buffer and also cannot edit it, do you have any ideas to support edit `search_paths` as other query as the `Search` or `Replace` or `Path`?

![image](https://github.com/nvim-pack/nvim-spectre/assets/42513619/9eb443e0-7b94-4d66-9c39-9ef11a8ac947)

**Comment by windwp** [comment]
you can't edit it. but you can change it when you open with command :Spectre cwd=......

**Comment by guanghechen** [comment]
Okay, but why not show the `searched_paths` field in the opened buffer? Since sometimes I don't known whether the words are really not exist in any file or the files are not under the serched_path.

**Comment by bemulima** [comment]
Bro, you read my mind and nailed it! That field made life so much easier for developers using nvim.
