### ISSUE TITLE
search stern word by regex 

### ISSUE THREAD

**Issue by bemulima** [nvim-pack/nvim-spectre#240]
For first thank so march for this awesome tool! You make life easy!

In my case I want to search `titleResponse` stern word but in result I see all words start of `titleResponse`. In result:
```
titleResponse
titleResponses
titleResponsePrint
titleResponseDownload
```

![image](https://github.com/nvim-pack/nvim-spectre/assets/5669814/f359968f-26f5-4e60-83a3-6a4927bbe47c)

I would like find all words of only `titleResponse` is this possible?

anchor `$` no help
![image](https://github.com/nvim-pack/nvim-spectre/assets/5669814/bf1a6779-7c01-4001-b381-080b5e5811c5)
![image](https://github.com/nvim-pack/nvim-spectre/assets/5669814/96b04f30-da92-4c90-9b4f-b3a909220dfe)

**Comment by windwp** [comment]
$ mean end of line.
i  use \btitleResponse\b but it only work if you change  a replace engine to "oxi". 

maybe you can change to search with  titleResponse[^\w]
