### ISSUE TITLE
Search match the whole word

### ISSUE THREAD

**Issue by RomaLzhih** [nvim-pack/nvim-spectre#248]
I see that we can search the word which matches the case, but is there any method to filter the search result that matches the whole word? Thanks.

**Comment by cksidharthan** [comment]
not sure what you mean by filter in the search result,

but there is an option to ignore the search result by doing a `dd` in the search result line to ignore a specific result

**Comment by RomaLzhih** [comment]
Ok, I see. Thanks. 
 I just noticed that we can use regex to search the word, lol. So search the whole word is done by \bword\b.
