### ISSUE TITLE
Error occurs when opening Spectre, if it's already open

### ISSUE THREAD

**Issue by asgeo1** [nvim-pack/nvim-spectre#36]
Calling `:lua require('spectre').open()` will open spectre.

But if I then call `:lua require('spectre').open()` a 2nd time (whilst it's already open), I get this error.

> E5108: Error executing lua ...site/pack/packer/start/nvim-spectre/lua/spectre/init.lua:109: Vim:Error executing lua callback: [string ":lua"]:1: Vim(call):E16: Invalid r
ange:  call s:RemoveRange(start, end) | endif

This error is tripping me up on a daily basis, as I have mapped the command to a shortcut and tend to use the shortcut whenever I want to search, regardless of whether Spectre is currently open or not.

**Comment by windwp** [comment]
you need check another plugin have function removerange on viml

**Comment by asgeo1** [comment]
Yup, you're right. It's the [vim-strip-trailing-whitespace](https://github.com/axelf4/vim-strip-trailing-whitespace) plugin causing the issue.

I've logged an issue with them [here](https://github.com/axelf4/vim-strip-trailing-whitespace/issues/8). I'll update this issue with a solution when I work it out.
