### ISSUE TITLE
file name with space won't work

### ISSUE THREAD

**Issue by qixiao986** [nvim-pack/nvim-spectre#60]
if the file name contains space,  search in file's path space doesn't escape, the result is empty. should use backslash to escape it.

**Comment by windwp** [comment]
space is use for search in multiple file type
you can search `*.ts *.tsx *.css`

**Comment by qixiao986** [comment]
> space is use for search in multiple file type you can search `*.ts *.tsx *.css`

if the file name contains space, like we have a file's name is "a b.txt", and we want to search in the file, the path shows: "a b.txt" which is not we want, should be "a\ b.txt", which will search in the file.

**Comment by qixiao986** [comment]
> > space is use for search in multiple file type you can search `*.ts *.tsx *.css`
> 
> if the file name contains space, like we have a file's name is "a b.txt", and we want to search in the file, the path shows: "a b.txt" which is not we want, should be "a\ b.txt", which will search in the file.

that means 
https://github.com/nvim-pack/nvim-spectre/blob/3bbf9cb2e36200d67c150d71d49011c133d3bbb8/lua/spectre/init.lua#L56 
should be
`        path = vim.fn.fnameescape(vim.fn.expand("%"))
`

**Comment by windwp** [comment]
you are right i think you talking about the path field on UI
