### ISSUE TITLE
Search not working on Macbook M1

### ISSUE THREAD

**Issue by truong-vonh-ostv** [nvim-pack/nvim-spectre#65]
Hi team, I got the issue like this when I using your `nvim-spectree` plugin.
I can't search anythings. Please help me to check that issue. Thanks all you guys!
The error response is below.
I'm using neovim `0.7.0`
`
E5108: Error executing lua ...site/pack/packer/start/nvim-spectre/lua/spectre/init.lua:551: attempt to get length of field 'search_query' (a nil value)
stack traceback:
        ...site/pack/packer/start/nvim-spectre/lua/spectre/init.lua:551: in function 'change_options'
        [string ":lua"]:1: in main chun
`

![image](https://user-images.githubusercontent.com/88626098/163718660-5d45886f-58ac-4983-8a14-822f6ec98160.png)

**Comment by windwp** [comment]
please provide a minimum config.
it work on my old macbook I don't have M1 :)

**Comment by truong-vonh-ostv** [comment]
Hi @windwp I just only simple config follow your documentation
`require('spectre').setup()` 
![image](https://user-images.githubusercontent.com/88626098/163742131-af177e02-103a-4b38-b73c-9dbfe8993931.png)
I installed `rg` and `sed` in my machine already. But It still didn't work :(

**Comment by chriztheanvill** [comment]
In linux fedora 35 also does not work, but if I set in Search:
```Search: player```
Then move the cursor like near the path and press the key x, works.

Note: I have installed rg, sed, ag

**Comment by windwp** [comment]
try put the cursor right below a text "Search" on UI then insert  text "player" and leave insert mode by <esc>.
