### ISSUE TITLE
Cannot toggle text searching when using ctrl + c to exit insert mode

### ISSUE THREAD

**Issue by lixiao189** [nvim-pack/nvim-spectre#67]
If a use ctrl + c to exit insert mode, the text searching will not toggle any more.

https://user-images.githubusercontent.com/44799572/164244675-0b071393-1d88-4202-aae3-51148ff1bc9c.mov

**Comment by windwp** [comment]
sorry  the only way to do that is esc. because <c-c> leave insert without event
you can map <c-c> to <esc> on file type spectre_panel
