### ISSUE TITLE
[feature request] `\zs` and `\ze` lookbehind and lookahead regex

### ISSUE THREAD

**Issue by tapyu** [nvim-pack/nvim-spectre#71]
On nvim cmd we can use the regex `\zs` and `\ze` to lookbehind and lookahead, respectively. It is not possible with `nvim-spectre` though...

# Expected behavior
In
```
foo bar baz
```
the regex `foo \zsbar` should match bar, as it does on `nvim`'s cmd.

# Actual behavior
It [nvim-spectre](https://github.com/nvim-pack/nvim-spectre) doesn't match anything....

**Comment by windwp** [comment]
#38  duplicate
