### ISSUE TITLE
What the parameters to open_cmd? I like so much this plugin but I want to windows open on the right side instead left

### ISSUE THREAD

**Issue by rafael-hs** [nvim-pack/nvim-spectre#74]
this file 
![image](https://user-images.githubusercontent.com/26948732/171953440-ca746048-8c92-44eb-8847-eb2799006d68.png)

**Comment by zdcthomas** [comment]
You might look into the splitright option. I'm not sure if you already have it set globally but that could do what you want

**Comment by rafael-hs** [comment]
I will try

**Comment by rafael-hs** [comment]
@zdcthomas thanks for reply, this worked  😄
