### ISSUE TITLE
Paths in Path?

### ISSUE THREAD

**Issue by EricDriussi** [nvim-pack/nvim-spectre#78]
Hi there! Really liking the plugin, thanks a lot!

Is it just me or the Path field only takes in filenames?
If I try to filter by directory it seems to not find anything.

Say I want to filter only the results within a directory called `lua`. 
No matter if I write `lua`, `*lua`, `lua*` or `*lua*`, it seems to only filter based on filenames (filetypes in this case with the `*lua` input).

Is that correct or am I missing something?

**Comment by windwp** [comment]
lua/**/*.lua
on readme . it use glob pattern
