### ISSUE TITLE
The interface doesn't show any replacement?

### ISSUE THREAD

**Issue by Integralist** [nvim-pack/nvim-spectre#81]
Not sure if I'm not triggering things correctly, but when I type my replacement and then press Esc nothing happens.

Here is the configuration I'm using:

```lua
lua <<EOF
  require('spectre').setup({
    replace_engine={
      ['sed']={
          cmd = "gsed", -- I brew install gsed but I still have the macOS BSD system `sed` installed/exposed.
      },
    },
  })
EOF
nnoremap <leader>S <cmd>lua require('spectre').open()<CR>
```

The below screenshot demonstrates that the replacement isn't applied in the preview.

For example, I expected all instances of `func Pr` to be replaced with `func Pxxxx`.  
So if we look at the first result `func PrintDictionaryItem` that should become `func PxxxintDictionaryItem`.

<img width="643" alt="Screenshot 2022-07-05 at 10 26 25" src="https://user-images.githubusercontent.com/180050/177296617-6a766b4a-4ddb-4546-9852-c67e881484ce.png">

**Comment by windwp** [comment]
you can't use '\b' it is vim regex you can check by ':help \s'.
I say it on README the search function use rg regex but the highlight on UI use vim regex :(

**Comment by Integralist** [comment]
Eurgh. Apologies. I did see mention of it but I clearly misunderstood what was actually being explained.

So yeah switching away from using 'word boundary' `\b` allowed the replacement to work 👍🏻

**Comment by gaborvecsei** [comment]
> Eurgh. Apologies. I did see mention of it but I clearly misunderstood what was actually being explained.
> 
> So yeah switching away from using 'word boundary' `\b` allowed the replacement to work 👍🏻

What was your solution to "switching away"?

**Comment by Integralist** [comment]
@gaborvecsei iirc I used `\<` and `\>` as that's the standard vim syntax for word boundaries.

**Comment by gaborvecsei** [comment]
@Integralist Yeah I tried it with the vim syntax, but then I got a `regex parse error`
<img width="777" alt="image" src="https://user-images.githubusercontent.com/18753533/200357643-4d4d40df-fac0-4a2c-a637-cf849b113de3.png">

**Comment by windwp** [comment]
hi  on new version you can try to switch replace engine to oxi
it use a rust  regex to highlight and replace.
just check readme and run file build.sh
