### ISSUE TITLE
bug(resume-last-search): not working

### ISSUE THREAD

**Issue by wongjiahau** [nvim-pack/nvim-spectre#92]
I tried to use the `resume last search` feature that was introduced in https://github.com/nvim-pack/nvim-spectre/commit/199b390f1a4d2b6228fa727ed1775d81bf6d48d2, however, I got the following error:

```
E5108: Error executing lua ...u/.config/nvim/plugged/nvim-spectre/lua/spectre/init.lua:275: attempt to index field 'query_backup' (a nil value)     
stack traceback:
        ...u/.config/nvim/plugged/nvim-spectre/lua/spectre/init.lua:275: in function 'resume_last_search'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Comment by windwp** [comment]
you need to search first then close spectre and open it again

**Comment by wongjiahau** [comment]
I'm not getting the error anymore after 6d877bc, however, it is still not working for me.

## Steps to reproduce
1. Open spectre (`:lua require("spectre").open()`)
2. Type `hello` under `Search:`
3. Close spectre (`:q`)
4. Open spectre again (`:lua require("spectre").open()`)
5. Press `<leader>l`

## Expected behavior
Expected `hello` to show under `Search:`

## Actual behavior
Nothing happens, the line below `Search:` is still empty.

## Neovim version
```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/neovim/build/config -I/neovim/src -I/neovim/.deps/usr/include -I/usr/include -I/neovim/build/src/nvim/auto -I/neovim/build/include
Compiled by root@29c055487d26

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

```

## Operating system
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

$ uname -m
aarch64
```

**Comment by windwp** [comment]
just open 1 file first

**Comment by wongjiahau** [comment]
@windwp I tried to `open 1 file first` but still not working

**Comment by fjchen7** [comment]
Have the same problem. Any fix about this?

**Comment by atomdmac** [comment]
I'm having the same issue as @wongjiahau .  There's no error or anything.  Neither the `<leader>l` keybind or manually calling the `resume_last_search` function seem to do anything.

**Comment by atomdmac** [comment]
It seems that `BufUnload` is not firing for some reason [here](https://github.com/nvim-pack/nvim-spectre/blob/b71b64afe9fedbfdd25a8abec897ff4af3bd553a/lua/spectre/init.lua#L161).  If I change this to use the `BufLeave` event, it _does_ work.
